###############################################################################
##
##  This file is part of the GenesisBack project, and is made available under
##  the terms of the GNU General Public License version 3.
##
##  Copyright (C) 2020 - Leo Karoubi
##
###############################################################################

local = $(CALLED_LOCAL_DIRECTORY)

TARGET_OBJECTS	+= $(addprefix $(local),	\
						quit.o				\
						help.o				\
						continue.o			\
						next.o				\
						dump.o				\
						regs.o				\
						burst.o				\
						breakpoint.o		\
					)
